name: Build project

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up ESP-IDF
      shell: powershell
      run: |
        git clone --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        ./install.ps1
        ./export.ps1

    - name: Checkout copilot-obd source code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build project
      shell: powershell
      run: |
        cd copilot-obd
        idf.py build
    