name: Build project

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Cache ESP-IDF
      id: cache-esp-idf
      uses: actions/cache@v3
      env:
        cache-name: cache-esp-idf
      with:
        path: ${{ github.workspace }}/esp-idf
        key: ${{ runner.os }}-${{ env.cache-name }}

    - name: Clone ESP-IDF
      if: ${{ steps.cache-esp-idf.outputs.cache-hit != 'true' }}
      uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}/esp-idf
        repository: espressif/esp-idf
        submodules: recursive

    - name: Cache ESP-IDF tools
      id: cache-esp-idf-tools
      uses: actions/cache@v3
      env:
        cache-name: cache-esp-idf-tools
      with:
        path: ~/.espressif
        key: ${{ runner.os }}-${{ env.cache-name }}
      
    - name: Install ESP-IDF
      if: ${{ steps.cache-esp-idf-tools.outputs.cache-hit != 'true' }}
      shell: powershell
      run: |
        cd ${{ github.workspace }}/esp-idf
        ./install.ps1

    - name: Cache copilot-obd
      id: cache-copilot-obd
      uses: actions/cache@v3
      env:
        cache-name: cache-copilot-obd
      with:
        path: ${{ github.workspace }}/copilot-obd
        key: ${{ runner.os }}-${{ env.cache-name }}

    - name: Clone copilot-obd
      if: ${{ steps.cache-copilot-obd.outputs.cache-hit != 'true' }}
      uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}/copilot-obd
        submodules: recursive

    - name: Cache build
      id: cache-build
      uses: actions/cache@v3
      env:
        cache-name: cache-build
      with:
        path: ${{ github.workspace }}/copilot-obd/build
        key: ${{ runner.os }}-${{ env.cache-name }}

    - name: Build project
      shell: powershell
      run: |
        cd ${{ github.workspace }}/copilot-obd
        ${{ github.workspace }}/esp-idf/export.ps1
        idf.py build
    